import uuid
from datetime import datetime
from sqlalchemy import Column, String, DateTime, Boolean, Integer
from sqlalchemy.orm import relationship
from app.database import Base

class User(Base):
    __tablename__ = "users"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    email = Column(String(255), unique=True, index=True, nullable=False)
    username = Column(String(100), unique=True, index=True, nullable=False)
    hashed_password = Column(String(255), nullable=False)
    full_name = Column(String(255), nullable=True)
    is_active = Column(Boolean, default=False)
    is_verified = Column(Boolean, default=False)
    verification_token_hash = Column(String(255), nullable=True)
    verification_token_expires_at = Column(DateTime, nullable=True)
    otp_code_hash = Column(String(255), nullable=True)
    otp_expires_at = Column(DateTime, nullable=True)
    otp_attempts = Column(Integer, default=0)
    last_otp_sent_at = Column(DateTime, nullable=True)
    verified_at = Column(DateTime, nullable=True)
    avatar_url = Column(String(500), nullable=True)
    password_reset_token_hash = Column(String(255), nullable=True)
    password_reset_expires_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    profile = relationship("PersonalProfile", back_populates="user", uselist=False, cascade="all, delete-orphan")
    conversations = relationship("Conversation", back_populates="user", cascade="all, delete-orphan")
    memories = relationship("Memory", back_populates="user", cascade="all, delete-orphan")
    documents = relationship("Document", back_populates="user", cascade="all, delete-orphan")
    vault_items = relationship("SecureVaultItem", back_populates="user", cascade="all, delete-orphan")
    activities = relationship("DailyActivity", back_populates="user", cascade="all, delete-orphan")
    audit_logs = relationship("AuditLog", back_populates="user", cascade="all, delete-orphan")
    connected_accounts = relationship("ConnectedAccount", back_populates="user", cascade="all, delete-orphan")
    github_repositories = relationship("GitHubRepository", back_populates="user", cascade="all, delete-orphan")
    agent_tasks = relationship("AgentTask", back_populates="user", cascade="all, delete-orphan")
    agent_reminders = relationship("AgentReminder", back_populates="user", cascade="all, delete-orphan")
    tool_logs = relationship("AgentToolLog", back_populates="user", cascade="all, delete-orphan")
    knowledge_entities = relationship("KnowledgeEntity", back_populates="user", cascade="all, delete-orphan")
    knowledge_relationships = relationship("KnowledgeRelationship", back_populates="user", cascade="all, delete-orphan")
    personal_goals = relationship("PersonalGoal", back_populates="user", cascade="all, delete-orphan")
    goal_milestones = relationship("GoalMilestone", back_populates="user", cascade="all, delete-orphan")
    study_subjects = relationship("StudySubject", back_populates="user", cascade="all, delete-orphan")
    study_topics = relationship("StudyTopic", back_populates="user", cascade="all, delete-orphan")
    study_sessions = relationship("StudySession", back_populates="user", cascade="all, delete-orphan")
    analytics_events = relationship("AnalyticsEvent", back_populates="user", cascade="all, delete-orphan")
    daily_briefs = relationship("DailyBrief", back_populates="user", cascade="all, delete-orphan")
    proactive_insights = relationship("ProactiveInsight", back_populates="user", cascade="all, delete-orphan")
    proactive_setting = relationship("ProactiveSetting", back_populates="user", uselist=False, cascade="all, delete-orphan")
    life_twin_snapshots = relationship("LifeTwinSnapshot", back_populates="user", cascade="all, delete-orphan")
    journal_entries = relationship("JournalEntry", back_populates="user", cascade="all, delete-orphan")
    project_health_records = relationship("ProjectHealthRecord", back_populates="user", cascade="all, delete-orphan")
    risk_events = relationship("RiskEvent", back_populates="user", cascade="all, delete-orphan")
    pattern_events = relationship("PatternEvent", back_populates="user", cascade="all, delete-orphan")
    decision_debate_sessions = relationship("DecisionDebateSession", back_populates="user", cascade="all, delete-orphan")
    bottleneck_records = relationship("BottleneckAnalysisRecord", back_populates="user", cascade="all, delete-orphan")
    device_alarms = relationship("DeviceAlarm", back_populates="user", cascade="all, delete-orphan")
